### ISSUE TITLE
Is this compatible with the CatGenie-120 PLUS

### ISSUE THREAD

**Issue by asalih** [davidhampgonsalves/CR14-emulator-for-CatGenie-120#1]
Hello thanks for the project, very good idea. I had a spare cartridge and turned out RFID is broken while changing the old one. So I have an arduino and I thought should I take the risk, why not? But mine is CG 120 plus, do you think is this works with this version?

**Comment by asalih** [comment]
Dude, thank you so much. It worked! Awesome.

**Comment by davidhampgonsalves** [comment]
Glad to hear, I couldn't find a cat genie 120 plus on the company site.

**Comment by asalih** [comment]
Oh I see this is some kind of marketing thing for Turkey. Thanks again.
