### ISSUE TITLE
Count reset after power outage

### ISSUE THREAD

**Issue by ghost** [davidhampgonsalves/CR14-emulator-for-CatGenie-120#11]
I'm assuming the cartridge count will reset to 120 if a power outage occurred. Or is the count stored in the eeprom? If not, could it be added? Other wise the cartridge could be empty while the count is still good and the user wouldn't know.

**Comment by davidhampgonsalves** [comment]
That's correct. It could be added but I probably personally won't since that's not an issue for me. If you are refilling cartridges the 120 limit probably isn't as relevant anyway since the viscosity of the cleaning fluid is probably different then the stock one.

**Comment by davidhampgonsalves** [comment]
I'd welcome a PR for this though if you decide to add it.
