### ISSUE TITLE
Invalid sigrok captures?

### ISSUE THREAD

**Issue by michaelcasson** [davidhampgonsalves/CR14-emulator-for-CatGenie-120#3]
I'm trying to open the .sr files in Sigrok but it only gives me "generic/unspecified error". It looks like maybe these are MacOS shortcut files or something. Can anyone else reproduce this?

**Comment by davidhampgonsalves** [comment]
Thanks for reporting this, I replaced them with the real files.

**Comment by michaelcasson** [comment]
That works, thanks!
