### ISSUE TITLE
Is there a bug? 

### ISSUE THREAD

**Issue by emrebayrak90** [davidhampgonsalves/CR14-emulator-for-CatGenie-120#4]
It is working very well after i connected the emulator but later when i start cleaning cycle it gives an cartridge error after 3-5 mins. I couldn't figured it out...

**Comment by davidhampgonsalves** [comment]
It sounds like its having an issue decrementing the usage count (thats what it does after it allows the process to start). I haven't had anyone else report this issue and my unit has been working normally for a couple months now.
