### ISSUE TITLE
Cable Pinning and Colors

### ISSUE THREAD

**Issue by EUA** [davidhampgonsalves/CR14-emulator-for-CatGenie-120#5]
> Unplug the CR14 and attach the I2C wires(white/black on my machine) to pins A4/A5 on the arduino and 5v power/ground(red/blue) to their respective pins.

On My Machine;

1. Pin - Red - +5V 
2. Pin - Black - GND
3. Pin - Blue - SDC
4. Pin - Yellow - SDA

This probably due about "RFID STYLE IDENTIFICATION" @ http://cartridgegenius.com/ page.
Regards.

**Comment by davidhampgonsalves** [comment]
thanks, I think they change the wires / colors over time.
