### ISSUE TITLE
Custom adapter PCB for Project

### ISSUE THREAD

**Issue by brett6320** [davidhampgonsalves/CR14-emulator-for-CatGenie-120#8]
I was able to leverage your project to bypass the DRM functions on my Cat Genie 120 - great work!

To tidy up the hardware side, I am having a custom PCB manufactured to connect the factory connector (for the RFID module in the Cat Genie 120) to the "default" pins on the Arduino Uno. This adapter board features the same socket as the RFID module to allow use without modifications to the factory wiring, other than minor re-routing.

Would you be interested in linking the materials list and/or Gerber package? If there's enough interest, I might look into selling kits or kits in various stages of assembly.

**Comment by davidhampgonsalves** [comment]
Sure, if you are still working on this.
